default: cpsc2150/labs/mortgages/*.java
	javac cpsc2150/labs/mortgages/MortgageApp.java

run: cpsc2150/labs/mortgages/MortgageApp.class
	java cpsc2150.labs.mortgages.MortgageApp

clean:
	rm -f cpsc2150/labs/mortgages/*.class
