default: src/cpsc2150/Speedster/DirectionalSpeedster.java src/cpsc2150/Speedster/IDirectionalSpeedster.java test/cpsc2150/Speedster/TestSpeedster.java
	javac -cp .:/usr/share/java/junit4.jar
src/cpsc2150/Speedster/DirectionalSpeedster.java src/cpsc2150/Speedster/IDirectionalSpeedster.java test/cpsc2150/Speedster/TestSpeedster.java

runtest: src/cpsc2150/Speedster/DirectionalSpeedster.class src/cpsc2150/Speedster/IDirectionalSpeedster.class test/cpsc2150/Speedster/TestSpeedster.class
	java  -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore
test/cpsc2150.Speedster.TestSpeedster

